# Ensure you run ./ebpf.sh before applying
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  imagePullSecrets: []
  kubernetesProvider: AKS
  calicoNetwork:
    bgp: Disabled
    containerIPForwarding: Enabled
    ipPools:
      - natOutgoing: Enabled
        encapsulation: VXLAN
        cidr: 10.244.0.0/16
    linuxDataplane: BPF
    hostPorts: null
  cni:
    ipam:
      type: Calico
    type: Calico
  registry: mcr.microsoft.com/
  imagePath: oss/calico
  controlPlaneTolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  typhaAffinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                  - system
          weight: 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "$API_SERVER_ENDPOINT"
  KUBERNETES_SERVICE_PORT: "$API_SERVER_PORT"
---
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true
  bpfExternalServiceMode: DSR